# Generated by Django 4.1.5 on 2023-07-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingmodel",
            name="latitude",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="parkingmodel",
            name="longitude",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
