# Generated by Django 4.1.5 on 2023-07-31 20:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("parking", "0003_alter_parkingspot_owner_reservation"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ParkingSpot",
            new_name="ParkingSpotModel",
        ),
        migrations.RenameModel(
            old_name="Reservation",
            new_name="ReservationModel",
        ),
    ]
